"""Emitting and reading profiles.

A profile is a document a user reads, argues with and edits by hand, so the
round trip has to preserve every value *and* every provenance note. A value lost
in serialisation shows up later as a finding on a deck that passed a moment
earlier, which is the worst way to discover a bug of this kind.
"""

from __future__ import annotations

import pytest

from tieout.learn.emit import (
    PROVENANCE_PREFIX,
    QUESTION_PREFIX,
    iter_provenance,
    render,
    write,
)
from tieout.profile.loader import (
    PROFILE_DIR_ENV,
    ProfileError,
    load,
    load_for_client,
    load_raw,
    load_suppressions,
    profile_dir,
    profile_path,
    read_comment_notes,
    suppression_path,
    write_suppressions,
)
from tieout.profile.schema import (
    Box,
    DeferredQuestion,
    FontRole,
    Profile,
    SlideProfile,
    Suppression,
    SuppressionFile,
)


def _profile() -> Profile:
    profile = Profile(
        client="acme",
        generated_at="2026-09-14",
        sources=["reference.pptx (26 slides)"],
        slide=SlideProfile(width_pt=960.0, height_pt=540.0),
        archetypes={"content": [1, 2, 3]},
    )
    profile.brand.palette_hex = ["#000000", "#1F3864"]
    profile.brand.fonts.allowed = ["Gill Sans MT"]
    profile.brand.fonts.roles = {"body": FontRole(min_pt=10.0, max_pt=14.0)}
    profile.set_provenance("brand.palette_hex", "two clusters across 26 slides", "high")
    profile.set_provenance("brand.fonts.allowed", "100% of characters", "high")
    profile.set_provenance("hygiene", "default, not inferred", "medium")
    return profile


# --------------------------------------------------------------------------------------
# Emitting
# --------------------------------------------------------------------------------------


def test_the_header_records_what_it_learned_from():
    text = render(_profile())
    assert text.startswith("# Generated by tieout learn on 2026-09-14 from:")
    assert "reference.pptx (26 slides)" in text


def test_every_note_appears_as_a_comment_beside_its_value():
    text = render(_profile())
    assert f"{PROVENANCE_PREFIX} two clusters across 26 slides" in text
    assert f"{PROVENANCE_PREFIX} 100% of characters" in text


def test_a_medium_confidence_value_says_so_in_its_comment():
    """A value the evidence only half supports should not read with the same
    authority as one derived from twenty-three slides."""
    assert "[confidence medium]" in render(_profile())


def test_a_deferred_question_is_written_above_the_field_it_concerns():
    profile = _profile()
    profile.questions = [
        DeferredQuestion(
            id="q1",
            field_path="brand.palette_hex",
            question="Is #1F3864 really the house navy?",
            options=["yes", "no"],
            default="yes",
        )
    ]
    text = render(profile)
    assert f"{QUESTION_PREFIX} Is #1F3864 really the house navy?" in text
    assert "Options: yes / no" in text
    assert "Defaulted to: yes" in text
    assert "1 of 1 questions" in text or "Answered 0 of 1" in text


def test_the_sections_whose_purpose_is_not_obvious_are_explained():
    text = render(_profile())
    assert "edit if a slide is wrong" in text
    assert "Silence is correct" in text
    assert "protected from re-learning" in text


def test_provenance_is_also_written_as_data_so_findings_can_cite_it():
    """It is written twice on purpose. Recovering it from comments alone
    mis-assigned notes across section boundaries, because YAML attaches a leading
    comment to the preceding sibling key."""
    text = render(_profile())
    assert "provenance:" in text
    assert "generated:" in text, "the duplication must be labelled as generated"


def test_writing_creates_the_directory(tmp_path):
    target = tmp_path / "nested" / "deeper" / "acme.yaml"
    result = write(_profile(), target)
    assert result.path == target
    assert target.exists()


def test_iter_provenance_is_sorted_and_complete():
    entries = list(iter_provenance(_profile()))
    paths = [path for path, _, _ in entries]
    assert paths == sorted(paths)
    assert ("hygiene", "default, not inferred", "medium") in entries


# --------------------------------------------------------------------------------------
# Reading
# --------------------------------------------------------------------------------------


def test_a_profile_survives_the_round_trip_intact(tmp_path):
    original = _profile()
    path = tmp_path / "acme.yaml"
    write(original, path)
    reloaded = load(path)

    assert reloaded.client == original.client
    assert reloaded.brand.palette_hex == original.brand.palette_hex
    assert reloaded.brand.fonts.roles["body"].describe() == "10pt to 14pt"
    assert reloaded.archetypes == original.archetypes
    assert reloaded.provenance == original.provenance
    assert reloaded.confidence == original.confidence


def test_each_note_stays_attached_to_its_own_value(tmp_path):
    """The bug that made the comments-only design untenable: a note must never
    migrate to a neighbouring section, because a finding citing the wrong
    evidence is worse than one citing none."""
    original = _profile()
    original.set_provenance("layout.grid", "edge clusters with support of 5", "high")
    original.set_provenance("layout.safe_margin_pt", "5th percentile of edges", "high")
    path = tmp_path / "acme.yaml"
    write(original, path)
    reloaded = load(path)

    assert reloaded.provenance_for("layout.grid") == "edge clusters with support of 5"
    assert reloaded.provenance_for("layout.safe_margin_pt") == "5th percentile of edges"


def test_provenance_falls_back_to_an_ancestor():
    profile = _profile()
    profile.set_provenance("brand.logo", "one image on 23 of 26 slides", "high")
    assert (
        profile.provenance_for("brand.logo.per_archetype.content")
        == "one image on 23 of 26 slides"
    )
    assert profile.provenance_for("nothing.here") is None


def test_a_missing_profile_says_where_it_looked(tmp_path):
    with pytest.raises(ProfileError, match="no profile at"):
        load(tmp_path / "absent.yaml")


def test_an_unparseable_profile_is_rejected_loudly(tmp_path):
    path = tmp_path / "broken.yaml"
    path.write_text("client: [unclosed\n", encoding="utf-8")
    with pytest.raises(ProfileError, match="not valid YAML"):
        load(path)


def test_a_profile_that_is_not_a_mapping_is_rejected(tmp_path):
    path = tmp_path / "list.yaml"
    path.write_text("- one\n- two\n", encoding="utf-8")
    with pytest.raises(ProfileError, match="does not contain a profile mapping"):
        load(path)


def test_an_invalid_profile_fails_at_load_rather_than_at_evaluation(tmp_path):
    """Validating late would surface a typo as a mysterious missing check halfway
    through an audit."""
    path = tmp_path / "wrong.yaml"
    path.write_text("client: acme\nslide:\n  width_pt: wide\n", encoding="utf-8")
    with pytest.raises(ProfileError, match="not a valid profile"):
        load(path)


def test_an_unknown_field_is_an_error_not_a_silent_no_op(tmp_path):
    """A misspelled key that loaded quietly would look like a configured rule and
    behave like an absent one."""
    path = tmp_path / "typo.yaml"
    path.write_text(
        "client: acme\nslide:\n  width_pt: 960\n  height_pt: 540\n"
        "brand:\n  pallete_hex: ['#000000']\n",
        encoding="utf-8",
    )
    with pytest.raises(ProfileError):
        load(path)


def test_load_for_client_resolves_the_profile_directory(tmp_path, monkeypatch):
    monkeypatch.setenv(PROFILE_DIR_ENV, str(tmp_path))
    assert profile_dir() == tmp_path
    write(_profile(), profile_path("acme"))
    assert load_for_client("acme").client == "acme"


def test_load_for_client_prefers_an_explicit_path(tmp_path, monkeypatch):
    monkeypatch.setenv(PROFILE_DIR_ENV, str(tmp_path / "ignored"))
    explicit = tmp_path / "elsewhere.yaml"
    write(_profile(), explicit)
    assert load_for_client("acme", explicit).client == "acme"


def test_a_missing_client_profile_explains_how_to_create_one(tmp_path, monkeypatch):
    monkeypatch.setenv(PROFILE_DIR_ENV, str(tmp_path))
    with pytest.raises(ProfileError, match="tieout learn"):
        load_for_client("ghost")


def test_top_level_comment_notes_can_be_read_back(tmp_path):
    """For `profile show` on a file a user has reformatted by hand."""
    path = tmp_path / "acme.yaml"
    write(_profile(), path)
    notes = read_comment_notes(load_raw(path))
    assert notes.get("slide") is None or isinstance(notes.get("slide"), str)
    assert isinstance(notes, dict)


# --------------------------------------------------------------------------------------
# Suppressions
# --------------------------------------------------------------------------------------


def test_a_missing_suppression_file_is_not_an_error(tmp_path, monkeypatch):
    monkeypatch.setenv(PROFILE_DIR_ENV, str(tmp_path))
    loaded = load_suppressions("acme")
    assert loaded.suppressions == []
    assert loaded.client == "acme"


def test_suppressions_round_trip_with_their_counts(tmp_path, monkeypatch):
    """The count is what lets section 8.7 notice a miscalibrated rule, so it has
    to survive the file."""
    monkeypatch.setenv(PROFILE_DIR_ENV, str(tmp_path))
    original = SuppressionFile(
        client="acme",
        suppressions=[Suppression(rule_id="BR-002", slide_index=5, count=3)],
    )
    write_suppressions(original, suppression_path("acme"))
    reloaded = load_suppressions("acme")
    assert reloaded.suppressions[0].count == 3
    assert reloaded.repeat_offenders()


def test_the_suppression_file_explains_itself(tmp_path, monkeypatch):
    monkeypatch.setenv(PROFILE_DIR_ENV, str(tmp_path))
    write_suppressions(SuppressionFile(client="acme"), suppression_path("acme"))
    text = suppression_path("acme").read_text()
    assert "miscalibrated" in text
    assert "learn --add" in text


def test_a_slide_scoped_suppression_only_matches_that_slide():
    suppressions = SuppressionFile(
        suppressions=[Suppression(rule_id="BR-002", slide_index=5)]
    )
    assert suppressions.matches("BR-002", 5)
    assert not suppressions.matches("BR-002", 6)
    assert not suppressions.matches("BR-003", 5)


def test_a_rule_scoped_suppression_matches_every_slide():
    suppressions = SuppressionFile(suppressions=[Suppression(rule_id="LO-004")])
    assert suppressions.matches("LO-004", 1)
    assert suppressions.matches("LO-004", 99)


def test_a_malformed_suppression_file_is_rejected(tmp_path, monkeypatch):
    monkeypatch.setenv(PROFILE_DIR_ENV, str(tmp_path))
    suppression_path("acme").parent.mkdir(parents=True, exist_ok=True)
    suppression_path("acme").write_text("suppressions: not-a-list\n", encoding="utf-8")
    with pytest.raises(ProfileError, match="not a valid suppression file"):
        load_suppressions("acme")


def test_an_empty_suppression_file_loads_as_empty(tmp_path, monkeypatch):
    monkeypatch.setenv(PROFILE_DIR_ENV, str(tmp_path))
    suppression_path("acme").parent.mkdir(parents=True, exist_ok=True)
    suppression_path("acme").write_text("", encoding="utf-8")
    assert load_suppressions("acme").suppressions == []


# --------------------------------------------------------------------------------------
# Schema behaviour
# --------------------------------------------------------------------------------------


def test_a_font_role_permits_only_what_it_states():
    exact = FontRole(exact_pt=[9.0, 10.0])
    assert exact.permits(9.0) and exact.permits(10.0)
    assert not exact.permits(11.0)

    band = FontRole(min_pt=10.0, max_pt=14.0)
    assert band.permits(10.0) and band.permits(12.0) and band.permits(14.0)
    assert not band.permits(9.0) and not band.permits(18.0)


def test_an_unconstrained_role_permits_nothing_rather_than_everything():
    """An empty band is an absence of evidence, and permitting everything would
    silently disable LO-007 for that role."""
    empty = FontRole()
    assert empty.is_empty
    assert not empty.permits(12.0)
    assert empty.describe() == "unconstrained"


def test_exact_sizes_are_normalised_on_construction():
    assert FontRole(exact_pt=[14.0, 10.0, 10.0]).exact_pt == [10.0, 14.0]


def test_a_box_describes_itself_in_the_units_a_designer_uses():
    described = Box(left=852, top=24, width=72, height=24, tolerance_pt=2.0).describe()
    assert "852pt" in described and "72x24pt" in described and "+/-2pt" in described


def test_locks_apply_to_descendants_but_not_to_siblings():
    profile = _profile()
    profile.locks = ["brand.logo"]
    assert profile.is_locked("brand.logo")
    assert profile.is_locked("brand.logo.per_archetype.content")
    assert not profile.is_locked("brand.logotype")
    assert not profile.is_locked("brand")


def test_the_archetype_of_a_slide_can_be_looked_up_both_ways():
    profile = _profile()
    assert profile.archetype_of(2) == "content"
    assert profile.archetype_of(99) is None


def test_a_severity_override_takes_effect():
    profile = _profile()
    assert profile.severity_of("BR-002", "major") == "major"
    profile.rules.severity_overrides["BR-002"] = "blocker"
    assert profile.severity_of("BR-002", "major") == "blocker"
