"""Writing the profile YAML, with provenance on every derived value.

The profile is the artefact that makes the tool trustworthy rather than
arbitrary. A user who is told "the logo should be at 852pt" has no reason to
believe it; a user who reads

    content: {left: 852, top: 24, width: 72, height: 24, tolerance_pt: 2.0}
    # logo geometry on 12 content slides, invariant with an observed spread of
    # 0.0pt giving a tolerance of 2pt

can check the claim against their own deck. So section 16's rule is absolute: if
the provenance comment cannot be written, the value is not emitted.

``ruamel.yaml`` in round-trip mode, so a user's own edits and comments survive
re-learning.

Provenance is written twice, deliberately: as ``why:`` comments above each value,
which is the document section 8.5 specifies and what a person actually reads, and
as a generated ``provenance`` block at the end of the file, which is what the
rules read to populate a finding's ``expected_provenance``.

The single-copy design -- comments only, recovered by the loader -- was built
first and abandoned. YAML attaches a leading comment to the *preceding* sibling
key, so recovery silently mis-assigned notes across section boundaries: a finding
about the grid cited the margin derivation. A finding that cites the wrong
evidence is worse than one that cites none, because the whole purpose of
provenance is to let the reader check the claim.
"""

from __future__ import annotations

import io
from collections.abc import Iterator
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Final

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq
from ruamel.yaml.scalarstring import DoubleQuotedScalarString

from tieout.profile.schema import Profile

#: Column the value-explaining comments are wrapped at.
_COMMENT_WIDTH: Final[int] = 84

#: Column the emitter folds scalars at. Named because :func:`_safe_key` has to
#: know it: a plain key folded at this column would not load back.
_WIDTH: Final[int] = 100

#: Prefix marking a question the interview deferred. Section 8.4 requires these
#: to appear above the field they concern so the user can find them.
QUESTION_PREFIX: Final[str] = "QUESTION:"

#: Prefix marking the provenance of a derived value, used by the loader to read
#: it back.
PROVENANCE_PREFIX: Final[str] = "why:"


def _yaml() -> YAML:
    handler = YAML()
    handler.default_flow_style = False
    handler.width = _WIDTH
    handler.indent(mapping=2, sequence=4, offset=2)
    handler.preserve_quotes = True
    return handler


@dataclass(frozen=True, slots=True)
class EmitResult:
    text: str
    path: Path | None = None


def render(profile: Profile, *, questions_deferred: int = 0) -> str:
    """Render a profile to YAML with a header and per-value provenance."""
    data = _commented(profile.model_dump(mode="json", exclude_none=True))
    assert isinstance(data, CommentedMap)

    annotate_indents(data)
    _attach_provenance(data, profile)
    _attach_questions(data, profile)
    _attach_section_notes(data, profile)

    stream = io.StringIO()
    stream.write(_header(profile, questions_deferred=questions_deferred))
    _yaml().dump(data, stream)
    return stream.getvalue()


def write(profile: Profile, path: str | Path, *, questions_deferred: int = 0) -> EmitResult:
    """Write a profile, creating the directory if needed."""
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    text = render(profile, questions_deferred=questions_deferred)
    target.write_text(text, encoding="utf-8")
    return EmitResult(text=text, path=target)


def _header(profile: Profile, *, questions_deferred: int) -> str:
    generated = profile.generated_at or datetime.now(UTC).strftime("%Y-%m-%d")
    lines = [f"# Generated by tieout learn on {generated} from:"]
    for source in profile.sources or ["(no source recorded)"]:
        lines.append(f"#   - {source}")

    answered = len([q for q in profile.questions if q.answered])
    total = len(profile.questions)
    if total:
        lines.append(
            f"# Answered {answered} of {total} questions."
            + (
                f" {questions_deferred or total - answered} deferred, see "
                f"{QUESTION_PREFIX} comments below."
                if total - answered
                else ""
            )
        )
    else:
        lines.append("# No questions: every rule was settled from the evidence.")
    lines.append(
        "#"
    )
    lines.append(
        "# Comments marked 'why:' record the evidence behind the value above them."
    )
    lines.append(
        "# They are regenerated by `tieout learn`; your own comments and edits are"
    )
    lines.append(
        "# preserved. Add a field path to `locks` to protect an edit from re-learning."
    )
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------------------
# Comment attachment
# --------------------------------------------------------------------------------------


def _commented(value: Any, depth: int = 0) -> Any:
    """Recursively convert plain containers to ruamel's commentable ones."""
    if isinstance(value, dict):
        out = CommentedMap()
        for key, item in value.items():
            out[_safe_key(key, depth)] = _commented(item, depth + 1)
        return out
    if isinstance(value, list):
        seq = CommentedSeq()
        for item in value:
            seq.append(_commented(item, depth + 1))
        return seq
    return value


def _safe_key(key: Any, depth: int) -> Any:
    """Quote a mapping key long enough that the emitter would fold it.

    ``provenance`` and ``confidence`` are keyed by field path, and a field path
    can carry deck text in its last segment --
    ``brand.footer.boilerplate.<the boilerplate itself>``. A real confidentiality
    footer is easily long enough to push that key past :data:`_WIDTH`, and the
    emitter folds a long *plain* scalar across lines. A value may span lines; a
    YAML simple key may not. So the profile ``learn`` had just written failed to
    load back, with a parse error naming a line in the generated ``provenance``
    block -- the one part of the file nobody hand-edits.

    Quoting is what keeps such a key on one line. It is applied only where it is
    needed, so the rest of the file stays the plain, readable document the
    profile is meant to be.
    """
    if not isinstance(key, str):
        return key
    # ``depth * 2`` is the emitted indent; ``+ 2`` covers the ": " that follows.
    if depth * 2 + len(key) + 2 <= _WIDTH:
        return key
    return DoubleQuotedScalarString(key)


def _navigate(root: CommentedMap, path: str) -> tuple[CommentedMap, str] | None:
    """Resolve a dotted path to the map holding it and the final key.

    Returns None when the path does not exist in the emitted document, which is
    normal: a provenance note may describe a value that was ultimately not
    emitted, and attaching its comment to nothing is better than crashing.
    """
    parts = path.split(".")
    current: Any = root
    for part in parts[:-1]:
        if not isinstance(current, CommentedMap) or part not in current:
            return None
        current = current[part]
    if not isinstance(current, CommentedMap) or parts[-1] not in current:
        return None
    return current, parts[-1]


def _attach_provenance(data: CommentedMap, profile: Profile) -> None:
    """Attach each provenance note to the value it explains.

    Deepest paths first, so a note on ``brand.logo.per_archetype.content`` lands
    on that key rather than being shadowed by a broader note on ``brand.logo``.
    """
    for path in sorted(profile.provenance, key=lambda p: (-p.count("."), p)):
        located = _navigate(data, path)
        if located is None:
            continue
        parent, key = located
        confidence = profile.confidence.get(path, "high")
        note = profile.provenance[path]
        if confidence != "high":
            note = f"{note} [confidence {confidence}]"
        _comment_before(parent, key, f"{PROVENANCE_PREFIX} {note}")


def _attach_questions(data: CommentedMap, profile: Profile) -> None:
    """Put every deferred question above the field it concerns."""
    for question in profile.questions:
        if question.answered:
            continue
        located = _navigate(data, question.field_path)
        if located is None:
            located = _navigate(data, question.field_path.rsplit(".", 1)[0])
        if located is None:
            continue
        parent, key = located
        lines = [f"{QUESTION_PREFIX} {question.question}"]
        if question.options:
            lines.append("Options: " + " / ".join(question.options))
        lines.append(
            f"Defaulted to: {question.default or '(none)'}. Confidence medium."
        )
        _comment_before(parent, key, *lines)


def _attach_section_notes(data: CommentedMap, profile: Profile) -> None:
    """Explain the sections whose purpose is not obvious from their name."""
    notes = {
        "archetypes": "learned slide classification; edit if a slide is wrong",
        "provenance": (
            "generated: the evidence behind each value, so a finding can tell you "
            "where its expectation came from. Mirrors the 'why:' comments above. "
            "Rewritten by `tieout learn`; editing it changes only what findings "
            "cite, not what they check"
        ),
        "confidence": "generated: how well evidenced each value is",
        "not_learned": (
            "rules deliberately not derived, and why. Silence is correct when the "
            "evidence is thin"
        ),
        "locks": (
            "field paths protected from re-learning. Add one after editing a "
            "value by hand, or run `tieout profile lock`"
        ),
        "questions": (
            "questions the interview raised. Answer them with "
            "`tieout learn --review`"
        ),
    }
    for key, note in notes.items():
        if key in data:
            _comment_before(data, key, note)

    discarded = profile.brand.palette_discarded
    if discarded and "brand" in data and isinstance(data["brand"], CommentedMap):
        _comment_before(
            data["brand"],
            "palette_discarded",
            "colours used too little to be brand colours, kept here so you can see",
            "what was discarded. These are NOT enforced.",
        )


def _comment_before(parent: CommentedMap, key: str, *lines: str) -> None:
    """Insert comment lines above ``key``, wrapping long ones.

    ``yaml_set_comment_before_after_key`` replaces any existing comment on the
    key, so everything for one key is gathered and written in a single call.
    """
    wrapped: list[str] = []
    for line in lines:
        wrapped.extend(_wrap(line, _COMMENT_WIDTH))
    if not wrapped:
        return
    indent = _indent_of(parent)
    existing = _existing_comment(parent, key)
    payload = "\n".join(existing + wrapped)
    parent.yaml_set_comment_before_after_key(key, before=payload, indent=indent)


def _existing_comment(parent: CommentedMap, key: str) -> list[str]:
    """Comment lines already sitting above a key, so user notes are not lost.

    A generated block is recognised and dropped, because the caller is about to
    write it again. Recognising only the *first* line of one -- the line opening
    with ``why:`` or ``QUESTION:`` -- is not enough: a long note wraps, and its
    continuation lines open with ordinary prose. Read as user comments, they
    were kept and the regenerated block was appended after them, so every
    re-learn left another orphaned fragment behind. Continuations are marked by
    :data:`_CONTINUATION_INDENT` when they are written, which is how they are
    told apart here.
    """
    token = parent.ca.items.get(key)
    if not token:
        return []
    out: list[str] = []
    for entry in token:
        if entry is None:
            continue
        for comment in entry if isinstance(entry, list) else [entry]:
            value = getattr(comment, "value", "")
            for line in str(value).splitlines():
                body = line.strip()
                if not body.startswith("#"):
                    continue
                body = body[1:]
                if body.strip() and _is_generated_continuation(body):
                    continue
                stripped = body.strip()
                if stripped and not stripped.startswith(
                    (PROVENANCE_PREFIX, QUESTION_PREFIX, "Options:", "Defaulted to:")
                ):
                    out.append(stripped)
    return out


def _is_generated_continuation(body: str) -> bool:
    """Whether a comment body is the wrapped continuation of a generated block."""
    without_gap = body[1:] if body.startswith(" ") else body
    return without_gap.startswith(_CONTINUATION_INDENT)


#: Map node -> indent column, populated by :func:`annotate_indents`.
#:
#: Kept out of band rather than set as an attribute on the node: ruamel's
#: CommentedMap has no slot for it, and a stray attribute would travel with the
#: document into anything that copies it.
_INDENTS: dict[int, int] = {}


def _indent_of(parent: CommentedMap) -> int:
    """The column a nested comment should start at.

    ruamel needs the column stated explicitly and mis-aligns nested comments
    without it.
    """
    return _INDENTS.get(id(parent), 0)


#: Indent on the second and later lines of a wrapped generated comment. It makes
#: a long note read as one block, and it is what
#: :func:`_is_generated_continuation` uses to tell a regenerated block from a
#: note the user wrote by hand.
_CONTINUATION_INDENT: Final[str] = "  "


def _wrap(text: str, width: int) -> list[str]:
    import textwrap

    return (
        textwrap.wrap(text, width=width, subsequent_indent=_CONTINUATION_INDENT)
        or [text]
    )


def annotate_indents(data: Any, depth: int = 0) -> None:
    """Record each map's nesting depth so comments indent correctly.

    Call before attaching any comment. The table is reset at the top level so a
    long-running process does not accumulate entries for collected documents.
    """
    if depth == 0:
        _INDENTS.clear()
    if isinstance(data, CommentedMap):
        _INDENTS[id(data)] = depth * 2
        for value in data.values():
            annotate_indents(value, depth + 1)
    elif isinstance(data, CommentedSeq):
        for value in data:
            annotate_indents(value, depth + 1)


def iter_provenance(profile: Profile) -> Iterator[tuple[str, str, str]]:
    """``(path, note, confidence)`` for every derived value, for ``profile show``."""
    for path in sorted(profile.provenance):
        yield path, profile.provenance[path], profile.confidence.get(path, "high")
